### ISSUE TITLE
Support for require.js optimizer?

### ISSUE THREAD

**Issue by sontek** [miracle2k/webassets#171]
Has there been any thought about supporting the r.js optimizer?

http://requirejs.org/docs/optimization.html

**Comment by andresmrm** [comment]
This can be closed, no? It was merged (https://github.com/miracle2k/webassets/pull/290) and is even in the docs.

But I'm having no luck in using it.
First because of this: https://github.com/miracle2k/webassets/issues/374
And even after hacking the code to use the right `modname`,  it seems not to rebuild when a JS file change.
I'm using it this way:

    requirejs = Bundle('js/config.js', filters='requirejs', output='gen/packed.js')

Where `config.js` is my requireJS config file, that has the `paths` and calls the main code with:

    requirejs(["app/main"])

And I'm also setting:

    REQUIREJS_BASEURL = "static/js"
    REQUIREJS_EXTRAS = "mainConfigFile=static/js/config.js include=requirejs"

**Comment by ornj** [comment]
@andresmrm [Use the depends argument](http://webassets.readthedocs.org/en/latest/bundles.html#bundles)

**Comment by andresmrm** [comment]
Thanks, @ornj !
