### ISSUE TITLE
Order of evaluation of files with Bundle

### ISSUE THREAD

**Issue by ShaneKilkelly** [miracle2k/webassets#280]
When using the Bundle class to compile coffeescript files (and presumably other transpiled languages), and using a wildcard specifier such as `"js/*.coffee"` , the order of evaluation of the files can differ between different platforms and file-systems. From our tests, this seems to be because the `glob` function behaves differently depending on the underlying file system.

This can be problematic when using Bundle in an AngularJS app (for example), where the order of compilation can matter.

Consider the following file structure:

```
/javascript/
    core.coffee
    directives.coffee
    services.coffee
```

One one system `glob("path/to/javascript/*.coffee")` yield the following:

```
['core.coffee', 'directives.coffee', 'services.coffee']
```

While on other file systems / platforms the result could be something like:

```
['directives.coffee', 'services.coffee', 'core.coffee']
```

... which will be evaluated in the wrong order and can lead to errors in the output javascript. So, when `Bundle("javascript/*.coffee", filters="...")` is run then the results can be wrong or broken on some platforms.

I propose that a change be made to the Bundle api to ensure that files found by glob are evaluated in sorted order by default regardless of platform or underlying filesystem. The GlobLoader class could probably be altered to always call `sorted()` on the results of glob before proceeding with compilation.

I believe this would help to guard against odd behaviours appearing when building assets on different platforms, which can be difficult to debug.

I've raised this issue to float the idea of stadardising on alphabetic-sorted ordering by default, before opening a pull-request. Any comments or counter-arguments welcome.

**Comment by aroberts** [comment]
I just got burned by this as well. Keeping the glob order stable across platforms is critical, in my opinion.  Otherwise, bundles have the potential to require that they be built on the web server in order for hash versioning to work.

I think nvie's idea is also pretty clean, and was how I initially assumed it would work.  I agree that it shouldn't respect nested bundles.  Ultimately, though, having stable globbing is pretty much essential for this package.  Has anyone made a patch or a version function?
