### ISSUE TITLE
UglifyJS filter producing empty files

### ISSUE THREAD

**Issue by mgill25** [miracle2k/webassets#339]
I'm using webassets via [Flask-Assets](https://github.com/miracle2k/flask-assets). I have:

`UglifyJS 2.4.15`
`webassets 0.11dev.`

The UglifyJS filter produces an empty file. Using the uglifyjs tool from the command line produces minified files as expected. Note: `jsmin` and `rjsmin` both also works as filters using the same setup. I tried providing the file location in the asset configuration as well, to no avail. :(

**Comment by rtxanson** [comment]
Pardon some thinking aloud-- I had the same issue and attempted to troubleshoot it. 

I suspect something like the following happens: 

 * I fail to configure webassets to use uglifyjs properly, and the compilation process runs, but results in a blank file
 * I attempt to fix the problem by adjusting uglifyjs configuration
 * webassets doesn't notice any source changes to the defined assets, because there are none; the target file isn't recompiled

After touching some of the source files, I seem to have triggered a recompilation with correct configuration, resulting in success.

**Comment by miracle2k** [comment]
This has been discussed elsewhere, but webassets should try to consider the filter configuration in the cache key.

Apart from that, it sees like the filter itself works.
