### ISSUE TITLE
Allow generated assets from python function 

### ISSUE THREAD

**Issue by eMerzh** [miracle2k/webassets#408]
I would like to include a JS file that is generated by a flask view by exemple

but i can't find a way to do this....
it would be great to add this possibility or to document it.

Thanks

**Comment by miracle2k** [comment]
You can include URLs.

To include, more generically, dynamically generated content: At least in principal the Bundle code was written with the intention of supporting objects other than filenames or urls. That may not be completely functional. But something along these lines is feasable:

    Bundle(
       'file.js', MemoryHunk(generate_content())
    )

A pull request to make this work is welcome.

**Comment by ornj** [comment]
The above doesn't work as @miracle2k said, but maybe something like this is good enough?

```py
def generate_content():
    return u"console.log('foo');"

bundle = MemoryHunk(generate_content())
bundle.save('path/to/generated/file')

Bundle('path/to/generated/file')
```

**Comment by ornj** [comment]
Elaborating on my comment above as by itself it's probably not going to do what you ultimately need it to.

I have a similar situation where I have a bundle with dynamically generated contents. Basically I'm analyzing all my Javascript entry points looking for modules/libraries that are used multiple times and creating a common bundle.

I use something like my comment above to generate a placeholder file in a place not tracked by version control. I'm doing this because `Bundle` requires content. Is there a better way to do this? Probably.

I then have a custom filter that does the work that `generate_content()` would do and i set `depends=**/*.js`.
