### ISSUE TITLE
CSSRewrite not generating relative paths anymore

### ISSUE THREAD

**Issue by WuShell** [miracle2k/webassets#418]
We recently upgraded to the latest webassets release in a pyramid-based project (from this forked version of webassets: https://github.com/graffic/webassets) and we noticed that the css bundles do not contain relative urls to static assets anymore (like images inside url()).

In our project, we have a library where all static assets are gathered, then we have different pyramid applications that reuse such library to share certain code, those assets and more. I've pushed a sampled version of the code here:

- Library: https://bitbucket.org/Wu/wlibrary
- App: https://bitbucket.org/Wu/wapp

I've also forked webassets and changed the relevant code that broke the relative path rewriting for us, here:

https://github.com/miracle2k/webassets/compare/master...WuShell:master 

Without that code, CSSRewrite finds the absolute full url provided by the pyramid_webassets resolver and use that as a base when rewriting, but this does not work well when you have to reuse the css bundle among multiple servers.

In our case, this happens in our testing environments, where we run some integration tests in parallel (py.test -n N), starting N wsgi servers serving the app in different urls (http://localhost:random_number_here) and then N phantomjs instances connecting to those servers and actually running the tests.

In such scenario, relative paths inside the css bundle work for every server/client (as the bundle file is the same for all of them), while having full urls means the urls will be overrided for each server/client when the bundle is generated:

url(("http://localhost:55551"); <- first server/client
url(("http://localhost:53234"); <- second server/client

and so on. When phantomjs on the first client loads a page, it gets the paths to the static assets served by the other server and... well, you probably realize the problem already.

My "fix" simply checks if we have full urls for both the output and the source and then if the scheme and hostname are the same. In such case, it lets relpath() to calculate the relative path to the static resource .

I'm not going to submit a PR (yet) because maybe I'm missing something and this can be fixed in some other way (passing some parameter to the webassets env, resolver... instead of changing the code). It would be great if someone with a better background on webassets can bring some light into it.

**Comment by miracle2k** [comment]
I don't understand the testing problem fully, but it seems to me that you are cheating a little bit here with the solution by using ``hostname`` instead of ``netloc``. That is, you are relying on "localhost:55551" and "localhost:53234" as being treated equivalent and thus "localhost:53234/foo.css" can link to "localhost:55551/bar.png" by simply doing ``url(bar.png)``.  This would not necessarily be true (though it all seems like an extreme edge case).

Basically, what we are talking about is this (thinking it through myself): A case where things are configured such that a source file is assigned an absolute url with a hostname.

Now the cssrewrite filter needs to generate a url to that file.

Since we know the absolute url to that file, we can just output it.

We can also try to be smart and if the output and source hosts are the same, we generate a relative url instead.

Is there a benefit to that? I'm not sure. Could one argue that we ignore the developer's wishes, you specified a host url for a reason? Maybe. 

I'm not sure if it's worth it, in particular if a proper implementation that takes into account port numbers doesn't really fix your problem.

Even if hosts are not involved, the cssrewrite filter could, I guess, just output the absolute path (e.g. ``/static/imgs/bar.png``) instead of trying to generate a relative one. It strikes me that the argument for attempting to generate a relative one, as we currently do (``../imgs/bar.png``) is that it makes the bundles slightly more portable. Maybe a similar argument could be made in support of this change.

**Comment by WuShell** [comment]
You are totally right, I should use netloc instead of hostname, so it takes care of the port too (thanks).

About our specific case here (which I'm aware is quite specific indeed), I've managed to fix it by making each test run to have a separate output for the bundled css file (in a similar way to what we already do to have separate wsgi processes serving the app in different port, we now put the bundled files in temporary-generated directories). That way we do not need this relative url "fix" anymore.

Now, if this is a good thing to have or not for CSSRewrite, I'm not sure neither. That's how it worked in previous versions of webassets and that's why I first thought on something like that to fix this problem (and I wanted to share it, just in case someone else could have found the same issue).

For us, it was needed to have a full url as the output for the css bundle, as it was served in a url defined as a static url in the pyramid project. Without that, the output resolved to simply the name of the bundled file, which could not be found at the root (/) when serving the app.

Then, when cssrewrite used that base full url to override the relative paths in url(); calls inside the css files, it worked just fine for us when serving the app, and it even worked fine for us when running our tests with a single process, because a wsgi server was started at a random port (say, localhost:54364) and all url(); calls inside those rewritten css files point to the proper static urls (http://localhost:54364/static/img/somefile.png). 

The problem appeared when running tests in parallel using py.test -n 3 (for example). Then, 3 different wsgi servers where started, listening on three different ports and py.test split the test runs between them. As the css bundle file had the same output for the three of them, urls rewritten by cssrewrite were being overriden with the urls of those three servers depending on which of the process was building the bundle. If then a request for http://localhost:54364 got the bundle which url(); addresses pointed to urls served by a different process (that maybe was not there anymore, as it could have finished running its tests already) we were getting lots of timeouts and ugly things on the headless browser side.

Anyway, thanks for the quick reply, it helped me clarifying some ideas.
